=== KevinTran1995/web-prog-2/libml/libml.dtd
<!-- DTD of a book organization language -->
<!ENTITY % URI "CDATA">

<!-- Document Structure -->
<!ELEMENT libml (book)+>
<!ELEMENT book (isbn, detail, writers)>

<!-- ISBN Structure -->
<!ELEMENT isbn (#PCDATA)>

<!-- Detail Structure -->
<!ELEMENT detail (name+, volume?, edition, publishDate, publishHouse)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT volume (#PCDATA)>
<!ELEMENT edition (#PCDATA)>
<!ELEMENT publishDate (#PCDATA)>
<!ELEMENT publishHouse (#PCDATA)>

<!-- Writers Structure -->
<!ELEMENT writers (author+, editor?)>

<!ELEMENT author (#PCDATA)>
<!ELEMENT editor (#PCDATA)>

<!-- Attribute Rules -->
<!ATTLIST libml 
xmlns %URI; "http://lskgfjv.linuxclass.marist.edu/libml/libml.dtd">

<!ATTLIST isbn type (10 | 13) "10">
  
<!ATTLIST edition type (softCover|hardCover|eBook) "softCover">

=== KevinTran1995/web-prog-2/libml/book_example.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- No style sheet yet...
<?xml-stylesheet href="" type="text/xsl"?>
-->

<!DOCTYPE book SYSTEM "http://lskgfjv.linuxclass.marist.edu/libml/libml.dtd">
<libml xmlns="http://lskgfjv.linuxclass.marist.edu/libml/libml.dtd">
	<book>
		<isbn type="10">
			1400050340
		</isbn>
		<detail>
			<title>Cheese: A Connoisseur's Guide to the World's Best</title>
			<!--<volume></volume>-->
			<edition type="hardCover"></edition>
			<publishDate>August 30, 2005</publishDate>
			<publishHouse>Clarkson Potter</publishHouse>
		</detail>
		<writers>
			<author>Max McCalman</author>
			<!--<editor></editor>-->
		</writers>
	</book>
</libml>
